export const GROWTH_DATA = {
  harvestQuality: [
    { parameter: 'Tamanho', value: 'Grande' },
    { parameter: 'Peso', value: '20g' },
    { parameter: 'Teor de Açúcar', value: '8 Brix' },
    { parameter: 'Cor', value: 'Vermelho Vivo' },
    { parameter: 'Incidência de Pragas', value: 'Baixa' },
    { parameter: 'Firmeza', value: 'Alta' },
    { parameter: 'Aroma', value: 'Intenso' },
    { parameter: 'Textura', value: 'Suave' },
    { parameter: 'Uniformidade de Cor', value: 'Uniforme' },
    { parameter: 'Presença de Defeitos', value: 'Sem Defeitos' },
    { parameter: 'Temperatura de Armazenamento', value: '2°C' },
    { parameter: 'Vida Útil', value: '7 dias' },
  ],
  production: [
    { label: 'Jan', value1: 500, value2: 100 },
    { label: 'Fev', value1: 450, value2: 120 },
    { label: 'Mar', value1: 600, value2: 80 },
    { label: 'Abr', value1: 550, value2: 90 },
    { label: 'Mai', value1: 620, value2: 110 },
    { label: 'Jun', value1: 580, value2: 130 },
    { label: 'Jul', value1: 610, value2: 100 },
    { label: 'Ago', value1: 570, value2: 140 },
    { label: 'Set', value1: 600, value2: 120 },
    { label: 'Out', value1: 620, value2: 110 },
    { label: 'Nov', value1: 650, value2: 90 },
    { label: 'Dez', value1: 700, value2: 80 },
  ],
  deliveryLoss: [
    { name: 'Produtos entregues', value: 6450 },
    { name: 'Produtos perdidos', value: 1370 },
  ],
}
