import { TraceabilityData } from './Traceability.types'

export const TRACEABILITY_DATA: TraceabilityData = {
  traceabilityMonthly: [
    {
      category: 'Histórico de Cultivo',
      records: [
        {
          name: 'Preparação do Solo',
          timestamp: 1690867200000,
          details:
            'Solo preparado para plantio com aragem e adição de fertilizantes NPK.',
          recordedBy: 'João Pedro',
          success: true,
        },
        {
          name: 'Plantio das mudas de morango',
          timestamp: 1690953600000,
          details: 'Plantio de 10.000 mudas da variedade Albion.',
          recordedBy: 'Jean Castro',
          success: true,
        },
        {
          name: 'Irrigação inicial para estabelecimento',
          timestamp: 1691040000000,
          details:
            'Primeira irrigação para garantir o estabelecimento das mudas.',
          recordedBy: 'Durval Andrade',
          success: true,
        },
        {
          name: 'Aplicação de fertilizantes de crescimento',
          timestamp: 1691126400000,
          details:
            'Aplicação de fertilizantes NPK para promover o crescimento.',
          recordedBy: 'Jean Castro',
          success: true,
        },
        {
          name: 'Controle de ervas daninhas',
          timestamp: 1691385600000,
          details:
            'Controle manual de ervas daninhas para evitar competição com as plantas de morango.',
          recordedBy: 'Joaquim Augusto',
          success: true,
        },
        {
          name: 'Monitoramento de pragas',
          timestamp: 1691731200000,
          details: 'Inspeção semanal para controle de pragas.',
          recordedBy: 'Eduardo Fiorito',
          success: true,
        },
        {
          name: 'Ajuste de irrigação conforme necessário',
          timestamp: 1692086400000,
          details:
            'Irrigação ajustada com base nas necessidades diárias das plantas.',
          recordedBy: 'Joaquim Augusto',
          success: true,
        },
        {
          name: 'Monitoramento de geadas',
          timestamp: 1692345600000,
          details: 'Monitoramento diário de geadas para proteger as plantas.',
          recordedBy: 'Eduardo Fiorito',
          success: true,
        },
        {
          name: 'Aplicação de fungicidas preventivos',
          timestamp: 1692691200000,
          details: 'Aplicação de fungicidas para prevenir doenças nas plantas.',
          recordedBy: 'Joaquim Augusto',
          success: true,
        },
        {
          name: 'Colheita manual',
          timestamp: 1693036800000,
          details: 'Colheita manual dos morangos maduros.',
          recordedBy: 'Eduardo Fiorito',
          success: true,
        },
        {
          name: 'Classificação e armazenamento dos frutos',
          timestamp: 1693382400000,
          details: 'Morangos classificados e armazenados a 4°C.',
          recordedBy: 'Joaquim Augusto',
          success: true,
        },
      ],
    },
    {
      category: 'Transporte e Armazenamento',
      records: [
        {
          name: 'Transporte para o armazém',
          timestamp: 1693382400000,
          details: '500 kg de morangos transportados a 4°C.',
          recordedBy: 'Costa LTDA.',
          success: true,
        },
        {
          name: 'Armazenamento no armazém',
          timestamp: 1693468800000,
          details: 'Morangos armazenados em câmara fria a 4°C.',
          recordedBy: 'TransferLog',
          success: true,
        },
      ],
    },
    {
      category: 'Pontos de Venda',
      records: [
        {
          name: 'Venda no mercado local',
          timestamp: 1693555200000,
          details: '300 kg de morangos vendidos no supermercado Marymel.',
          recordedBy: 'Vendedor do supermercado',
          success: true,
        },
        {
          name: 'Venda no supermercado',
          timestamp: 1693641600000,
          details: '200 kg de morangos vendidos no Supermarket Irmão Almeida.',
          recordedBy: 'Gerente do supermercado',
          success: true,
        },
      ],
    },
  ],
  salesMonthly: [
    { name: 'Supermercado', value: 200 },
    { name: 'CEASA', value: 150 },
    { name: 'Feirantes', value: 100 },
  ],
  transportData: [
    {
      vehicle: 'CAM-88',
      status: 'Na rota',
      currentRoute: 'CAM-88 (Fazenda -> Armazém)',
      temperature: 4,
      alerts: { text: 'Nenhum', status: 'success' },
      departureTime: 1693382400000,
      arrivalTime: 1693396800000,
      duration: 240,
    },
    {
      vehicle: 'CAM-92',
      status: 'Fora de rota',
      currentRoute: 'CAM-92 (Armazém -> Supermercado)',
      temperature: 6,
      humidity: 90,
      alerts: { text: 'Alerta de temperatura', status: 'warning' },
      departureTime: 1693382400000,
      arrivalTime: 1693396800000,
      duration: 240,
    },
    {
      vehicle: 'CAM-95',
      status: 'Na rota',
      currentRoute: 'CAM-95 (Fazenda -> Mercado Local)',
      temperature: 5,
      humidity: 80,
      alerts: { text: 'Nenhum', status: 'success' },
      departureTime: 1693400000000,
      arrivalTime: 1693414400000,
      duration: 240,
    },
    {
      vehicle: 'CAM-66',
      status: 'Parado',
      currentRoute: 'CAM-66 (Armazém -> Distribuidor)',
      temperature: 3,
      humidity: 88,
      alerts: { text: 'Problema mecânico', status: 'error' },
      departureTime: 1693420000000,
      arrivalTime: 1693434400000,
      duration: 240,
    },
    {
      vehicle: 'CAM-26',
      status: 'Na rota',
      currentRoute: 'CAM-26 (Fazenda -> CEASA)',
      temperature: 4,
      humidity: 85,
      alerts: { text: 'Nenhum', status: 'success' },
      departureTime: 1693440000000,
      arrivalTime: 1693454400000,
      duration: 240,
    },
    {
      vehicle: 'CAM-33',
      status: 'Fora de rota',
      currentRoute: 'CAM-33 (Distribuidor -> Supermercado)',
      temperature: 6,
      humidity: 90,
      alerts: { text: 'Alerta de temperatura', status: 'warning' },
      departureTime: 1693460000000,
      arrivalTime: 1693474400000,
      duration: 240,
    },
    {
      vehicle: 'CAM-88',
      status: 'Na rota',
      currentRoute: 'CAM-88 (CEASA -> Mercado Local)',
      temperature: 5,
      humidity: 80,
      alerts: { text: 'Nenhum', status: 'success' },
      departureTime: 1693480000000,
      arrivalTime: 1693494400000,
      duration: 240,
    },
    {
      vehicle: 'CAM-42',
      status: 'Parado',
      currentRoute: 'CAM-42 (Armazém -> Supermercado)',
      temperature: 3,
      humidity: 88,
      alerts: { text: 'Problema mecânico', status: 'error' },
      departureTime: 1693500000000,
      arrivalTime: 1693514400000,
      duration: 240,
    },
  ],
  transportTitles: [
    'Veículo',
    'Status',
    'Rota Atual',
    'Temperatura (°C)',
    'Alertas',
    'Hora de Partida',
    'Hora de Chegada',
    'Duração',
  ],
}
